### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by MoltenCoreDev** [ClientModder1992/vizality#1]
fuck you you fucking leaker get fucked I hope ur family dies and you too kthxbye

**Comment by 1Lighty** [comment]
mad?

**Comment by ClientModder1992** [comment]
![image](https://user-images.githubusercontent.com/80854175/113368318-6fe42980-932c-11eb-9515-51d2fa67b679.png)

**Comment by Cynosphere** [comment]
based (on the gnu general public license v3.0)
